modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="super_disc"
version="${version}"
displayName="Super Disc"
description='''Shared MP3 and Ogg Vorbis playback through vanilla jukeboxes.'''
[[dependencies.super_disc]]
modId="neoforge"
type="required"
versionRange="[21.1.251,21.2)"
ordering="NONE"
side="BOTH"
[[dependencies.super_disc]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
