modLoader="javafml"
loaderVersion="[52,)"
license="All Rights Reserved"
[[mods]]
modId="super_disc"
version="${version}"
displayName="Super Disc"
description='''Shared MP3 and Ogg Vorbis playback through vanilla jukeboxes.'''
[[dependencies.super_disc]]
modId="forge"
mandatory=true
versionRange="[52.1.16,53)"
ordering="NONE"
side="BOTH"
[[dependencies.super_disc]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"
